### Word Embedding 

In [1]:
#import necessary libraries
from tensorflow.keras.preprocessing.text import one_hot

2022-03-18 19:55:09.396153: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-03-18 19:55:09.396205: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
## Sentences
sent = ['the glass of the milk',
       'the glass of the juice',
       'the cup of tea',
       'I am a good boy',
       'I am a good developer',
       'understand the meaning of words',
       'your videos are good']

In [3]:
sent

['the glass of the milk',
 'the glass of the juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
#define the vocabulary size | dictionary 
voc_size = 10000

### One hot representation

In [5]:
onehot_repr = [one_hot(words, voc_size) for words in sent]
print(onehot_repr)

[[8839, 7985, 5387, 8839, 4054], [8839, 7985, 5387, 8839, 604], [8839, 2752, 5387, 1043], [7976, 2240, 7317, 9452, 5724], [7976, 2240, 7317, 9452, 3991], [3216, 8839, 1566, 5387, 6915], [7344, 6284, 132, 9452]]


### Word Embedding Representation

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [9]:
sent_length = 8
embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen = sent_length)
print(embedded_docs)

[[   0    0    0 8839 7985 5387 8839 4054]
 [   0    0    0 8839 7985 5387 8839  604]
 [   0    0    0    0 8839 2752 5387 1043]
 [   0    0    0 7976 2240 7317 9452 5724]
 [   0    0    0 7976 2240 7317 9452 3991]
 [   0    0    0 3216 8839 1566 5387 6915]
 [   0    0    0    0 7344 6284  132 9452]]


In [10]:
dim=10

In [11]:
#build model
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam','mse')

2022-03-18 20:10:15.811477: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-03-18 20:10:15.811525: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-03-18 20:10:15.811563: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (catalina): /proc/driver/nvidia/version does not exist


In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 15)             150000    
                                                                 
Total params: 150,000
Trainable params: 150,000
Non-trainable params: 0
_________________________________________________________________


In [13]:
print(model.predict(embedded_docs))

[[[-0.01600979  0.00312096 -0.04396638  0.03627886 -0.0349185
   -0.02516865 -0.03782571  0.02405502  0.02214814 -0.00281483
    0.01507786  0.02916223  0.03611392  0.00793301 -0.03033689]
  [-0.01600979  0.00312096 -0.04396638  0.03627886 -0.0349185
   -0.02516865 -0.03782571  0.02405502  0.02214814 -0.00281483
    0.01507786  0.02916223  0.03611392  0.00793301 -0.03033689]
  [-0.01600979  0.00312096 -0.04396638  0.03627886 -0.0349185
   -0.02516865 -0.03782571  0.02405502  0.02214814 -0.00281483
    0.01507786  0.02916223  0.03611392  0.00793301 -0.03033689]
  [-0.00394354 -0.02544268 -0.04179453  0.04624308 -0.04979689
    0.0244992   0.00635908 -0.04043717  0.00285687  0.0183841
    0.00256523  0.00482646  0.03445486  0.00141786 -0.00495438]
  [-0.00554899 -0.03667738 -0.02463427  0.03838489 -0.01730816
    0.04947313 -0.02067232  0.00905544 -0.04973225  0.02086634
   -0.03241809 -0.00188866  0.01878399  0.00016651  0.04241934]
  [ 0.01455828 -0.00399232  0.0053132  -0.00535119 -0.

In [14]:
embedded_docs[0]

array([   0,    0,    0, 8839, 7985, 5387, 8839, 4054], dtype=int32)

In [15]:
print(model.predict(embedded_docs)[0])

[[-0.01600979  0.00312096 -0.04396638  0.03627886 -0.0349185  -0.02516865
  -0.03782571  0.02405502  0.02214814 -0.00281483  0.01507786  0.02916223
   0.03611392  0.00793301 -0.03033689]
 [-0.01600979  0.00312096 -0.04396638  0.03627886 -0.0349185  -0.02516865
  -0.03782571  0.02405502  0.02214814 -0.00281483  0.01507786  0.02916223
   0.03611392  0.00793301 -0.03033689]
 [-0.01600979  0.00312096 -0.04396638  0.03627886 -0.0349185  -0.02516865
  -0.03782571  0.02405502  0.02214814 -0.00281483  0.01507786  0.02916223
   0.03611392  0.00793301 -0.03033689]
 [-0.00394354 -0.02544268 -0.04179453  0.04624308 -0.04979689  0.0244992
   0.00635908 -0.04043717  0.00285687  0.0183841   0.00256523  0.00482646
   0.03445486  0.00141786 -0.00495438]
 [-0.00554899 -0.03667738 -0.02463427  0.03838489 -0.01730816  0.04947313
  -0.02067232  0.00905544 -0.04973225  0.02086634 -0.03241809 -0.00188866
   0.01878399  0.00016651  0.04241934]
 [ 0.01455828 -0.00399232  0.0053132  -0.00535119 -0.01887563 -0.0